In [1]:
# load package
from cryptory import Cryptory
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.plotly as py
import plotly.graph_objs as go
import ssl

ssl._create_default_https_context = ssl._create_unverified_context
np.set_printoptions(suppress=True)

In [2]:
# initialise object 
# pull data from start of 2017 to present day
my_cryptory = Cryptory(from_date = "2017-01-01")

# get historical bitcoin prices from coinmarketcap
my_cryptory.extract_coinmarketcap("bitcoin").head()

date     open     high      low    close       volume     marketcap
0 2019-05-04  5769.20  5886.89  5645.47  5831.17  17567780766  103112021259
1 2019-05-03  5505.55  5865.88  5490.20  5768.29  18720780006  101986240859
2 2019-05-02  5402.42  5522.26  5394.22  5505.28  14644460907   97330112147
3 2019-05-01  5350.91  5418.00  5347.65  5402.70  13679528236   95501110091
4 2019-04-30  5247.73  5363.26  5224.19  5350.73  13878964574   94573826827

In [3]:
all_coins_df = my_cryptory.extract_bitinfocharts("btc")
# coins of interest
bitinfocoins = ["btc", "eth", "xrp", "ltc", "dash", "xmr", "doge"]
for coin in bitinfocoins[1:]:
    all_coins_df = all_coins_df.merge(my_cryptory.extract_bitinfocharts(coin), on="date", how="left")

In [4]:
all_coins_df = all_coins_df.fillna(0)
all_coins_df.set_index('date',inplace=True)
all_coins_df.insert(0,"usd_price",1)
all_coins_df = all_coins_df.reindex(index=all_coins_df.index[::-1])
all_coins_df.head()

usd_price  btc_price  eth_price  xrp_price  ltc_price  dash_price  \
date                                                                            
2017-01-01          1    970.988      8.233    0.00651      4.389      11.356   
2017-01-02          1   1010.000      8.182    0.00640      4.539      11.593   
2017-01-03          1   1017.000      8.811    0.00632      4.525      12.383   
2017-01-04          1   1075.000     10.440    0.00642      4.585      14.748   
2017-01-05          1   1045.000     10.479    0.00650      4.404      14.815   

            xmr_price  doge_price  
date                               
2017-01-01     13.532    0.000224  
2017-01-02     14.671    0.000222  
2017-01-03     16.125    0.000220  
2017-01-04     16.807    0.000226  
2017-01-05     16.713    0.000225

In [5]:
tokens = all_coins_df.columns.tolist()
tokens

['usd_price',
 'btc_price',
 'eth_price',
 'xrp_price',
 'ltc_price',
 'dash_price',
 'xmr_price',
 'doge_price']

In [6]:
all_coins_df.tail()

usd_price  btc_price  eth_price  xrp_price  ltc_price  dash_price  \
date                                                                            
2019-05-01          1     5354.0    161.126      0.305     73.231     114.102   
2019-05-02          1     5432.0    160.495      0.304     73.269     116.763   
2019-05-03          1     5704.0    166.240      0.309     77.391     119.319   
2019-05-04          1     5750.0    164.132      0.302     77.448     120.244   
2019-05-05          1     5773.0    163.159      0.302     76.631     118.753   

            xmr_price  doge_price  
date                               
2019-05-01     63.580     0.00250  
2019-05-02     64.995     0.00257  
2019-05-03     66.477     0.00266  
2019-05-04     67.009     0.00264  
2019-05-05     67.711     0.00262

In [7]:
all_coins_df.index

DatetimeIndex(['2017-01-01', '2017-01-02', '2017-01-03', '2017-01-04',
               '2017-01-05', '2017-01-06', '2017-01-07', '2017-01-08',
               '2017-01-09', '2017-01-10',
               ...
               '2019-04-26', '2019-04-27', '2019-04-28', '2019-04-29',
               '2019-04-30', '2019-05-01', '2019-05-02', '2019-05-03',
               '2019-05-04', '2019-05-05'],
              dtype='datetime64[ns]', name='date', length=855, freq=None)

In [8]:
data = []

coinNames = iter(all_coins_df)
next(coinNames)

for index, coin in enumerate(tokens):
    coin_chart_info = go.Scatter(
        x = all_coins_df.index,
        y = all_coins_df[coin].tolist(),
        mode = 'lines',
        name = coin[:-6])
    data.append(coin_chart_info)
    tokens[index] = coin[:-6]

In [9]:
layout = go.Layout(
    title = "Historic Price Over Time",
    autosize=True,
    showlegend=True,
    legend=dict(x=0.9, y=0.9))

fig = dict(data=data, layout = layout)
py.iplot(fig, filename='stacked-area-plot-hover')

/Users/chris/Google Drive/Uct/Academic/Financial Software Engineering/Take Home exam/Answers/Q3/CryptoPortfolioTester/venv/lib/python3.7/site-packages/IPython/core/display.py:689: UserWarning:

Consider using IPython.display.IFrame instead



In [10]:
initial_price = all_coins_df.head(1)
initial_price

usd_price  btc_price  eth_price  xrp_price  ltc_price  dash_price  \
date                                                                            
2017-01-01          1    970.988      8.233    0.00651      4.389      11.356   

            xmr_price  doge_price  
date                               
2017-01-01     13.532    0.000224

In [11]:
initial_price = np.array(initial_price)[0]
initial_price

array([  1.      , 970.988   ,   8.233   ,   0.00651 ,   4.389   ,
        11.356   ,  13.532   ,   0.000224])

In [12]:
INVEST = 1000

In [13]:
initial_weights = np.ones(len(tokens)) / len(tokens)
initial_weights

array([0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125])

In [14]:
initial_allocation = INVEST * initial_weights / initial_price
initial_allocation[np.isinf(initial_allocation)] = 0
initial_allocation

array([   125.        ,      0.12873486,     15.18280092,  19201.22887865,
           28.48029164,     11.00739697,      9.23736329, 558035.71428571])

In [15]:
initial_positions = initial_allocation * initial_price
initial_positions

array([125., 125., 125., 125., 125., 125., 125., 125.])

In [16]:
initial_portfolio_value = initial_positions.sum().sum()
initial_portfolio_value

1000.0

In [17]:
tokens

['usd', 'btc', 'eth', 'xrp', 'ltc', 'dash', 'xmr', 'doge']

In [18]:
hodl = {}
rb = {}

current_allocation = initial_allocation

for i, current_price in all_coins_df.iterrows():
    # hodl positions
    hodl[i] = initial_allocation * current_price
    
    # current positions
    current_positions = current_allocation * current_price
    rb[i] = current_positions
    
    # rebalance
    current_portfolio_value = current_positions.sum()
    if(current_price.min() > 0):
        current_allocation = current_portfolio_value * initial_weights / current_price

In [19]:
hodl = pd.DataFrame(hodl).T
rb = pd.DataFrame(rb).T

In [22]:
all_coins_df.min()

usd_price       1.000000
btc_price     781.292000
eth_price       8.182000
xrp_price       0.000000
ltc_price       3.729000
dash_price      0.000000
xmr_price      10.490000
doge_price      0.000201
dtype: float64

In [23]:
hodl_value = hodl.sum(axis=1)
rb_value = rb.sum(axis=1)

hodl_perf = hodl_value.iloc[-1] / hodl_value.iloc[0]
rb_perf = rb_value.iloc[-1] / rb_value.iloc[0]

In [24]:
hodlInfo = go.Scatter(
        x = hodl_value.index,
        y = hodl_value.tolist(),
        mode = 'lines',
        name = 'hodl {:.1f}%'.format(hodl_perf * 100))

rebalanceInfo = go.Scatter(
        x = rb_value.index,
        y = rb_value.tolist(),
        mode = 'lines',
        name = 'rebalance {:.1f}%'.format(rb_perf * 100))

In [25]:
layout = go.Layout(
    title = "Portfolio value over time",
    autosize=True,
    showlegend=True,
    legend=dict(x=0.8, y=0.9))

fig = dict(data=[hodlInfo, rebalanceInfo], layout = layout)
py.iplot(fig)

In [78]:
funds = [
    {
    'coins': ['eth_price', 'btc_price', 'usd_price'],
    'ratio': [0.4, 0.4, 0.2],
    'rebalance': 7,
    'name': 'ETH40, BTC40, USD20 @ 7',
    },
    {
    'coins': ['eth_price', 'btc_price', 'usd_price'],
    'ratio': [0.25, 0.25, 0.5],
    'rebalance': 30,
    'name': 'ETH25, BTC25, USD50 @ 30',
    },
    {
    'coins': ['eth_price', 'btc_price'],
    'ratio': [0.5, 0.5],
    'rebalance': 15,
    'name': 'ETH50, BTC50 @ 15',
    },
    {
    'coins': ['eth_price', 'btc_price'],
    'ratio': [0.5, 0.5],
    'rebalance': 0,
    'name': 'ETH50, BTC50 @ HODL',
    },
    {
    'coins': ['eth_price'],
    'ratio': [1],
    'rebalance': 0,
    'name': 'ETH100 @ HODL',
    },
    {
    'coins': ['btc_price'],
    'ratio': [1],
    'rebalance': 0,
    'name': 'BTC100 @ HODL',
    }]

In [79]:
fund_returns = {}
for index, fund in enumerate(funds):
    
    coin_prices = all_coins_df.loc[:,fund['coins']]
    
    fund_initial_weights = np.array(fund['ratio'])
    
    fund_initial_price = coin_prices.head(1)
    fund_initial_price = np.array(fund_initial_price)[0]
    
    fund_initial_allocation = INVEST * fund_initial_weights / fund_initial_price
    fund_initial_allocation[np.isinf(fund_initial_allocation)] = 0
    
    fund_initial_positions = fund_initial_allocation * fund_initial_price
        
    fund_current_allocation = fund_initial_allocation
    
    day_count = 1
    fund_returns[fund['name']] = {}
    for i, current_price in coin_prices.iterrows():
        fund_current_positions = fund_current_allocation * current_price
        fund_returns[fund['name']][i] = fund_current_positions

        # rebalance
        current_portfolio_value = fund_current_positions.sum()
        if day_count > fund['rebalance'] and current_price.min() > 0:
            #update the allocation for each token (preform the rebalance)
            fund_current_allocation = current_portfolio_value * fund_initial_weights / current_price
            #restart counting for next rebalance
            day_count = 1
        #increment time
        day_count += 1

7
1
7
2
7
3
7
4
7
5
7
6
7
7
7
8
7
2
7
3
7
4
7
5
7
6
7
7
7
8
7
2
7
3
7
4
7
5
7
6
7
7
7
8
7
2
7
3
7
4
7
5
7
6
7
7
7
8
7
2
7
3
7
4
7
5
7
6
7
7
7
8
7
2
7
3
7
4
7
5
7
6
7
7
7
8
7
2
7
3
7
4
7
5
7
6
7
7
7
8
7
2
7
3
7
4
7
5
7
6
7
7
7
8
7
2
7
3
7
4
7
5
7
6
7
7
7
8
7
2
7
3
7
4
7
5
7
6
7
7
7
8
7
2
7
3
7
4
7
5
7
6
7
7
7
8
7
2
7
3
7
4
7
5
7
6
7
7
7
8
7
2
7
3
7
4
7
5
7
6
7
7
7
8
7
2
7
3
7
4
7
5
7
6
7
7
7
8
7
2
7
3
7
4
7
5
7
6
7
7
7
8
7
2
7
3
7
4
7
5
7
6
7
7
7
8
7
2
7
3
7
4
7
5
7
6
7
7
7
8
7
2
7
3
7
4
7
5
7
6
7
7
7
8
7
2
7
3
7
4
7
5
7
6
7
7
7
8
7
2
7
3
7
4
7
5
7
6
7
7
7
8
7
2
7
3
7
4
7
5
7
6
7
7
7
8
7
2
7
3
7
4
7
5
7
6
7
7
7
8
7
2
7
3
7
4
7
5
7
6
7
7
7
8
7
2
7
3
7
4
7
5
7
6
7
7
7
8
7
2
7
3
7
4
7
5
7
6
7
7
7
8
7
2
7
3
7
4
7
5
7
6
7
7
7
8
7
2
7
3
7
4
7
5
7
6
7
7
7
8
7
2
7
3
7
4
7
5
7
6
7
7
7
8
7
2
7
3
7
4
7
5
7
6
7
7
7
8
7
2
7
3
7
4
7
5
7
6
7
7
7
8
7
2
7
3
7
4
7
5
7
6
7
7
7
8
7
2
7
3
7
4
7
5
7
6
7
7
7
8
7
2
7
3
7
4
7
5
7
6
7
7
7
8
7
2
7
3
7
4
7
5
7
6
7
7
7
8
7
2
7
3
7
4
7
5
7
6
7
7
7
8
7
2
7
3
7
4
7
5


15
2
15
3
15
4
15
5
15
6
15
7
15
8
15
9
15
10
15
11
15
12
15
13
15
14
15
15
15
16
15
2
15
3
15
4
15
5
15
6
15
7
15
8
15
9
15
10
15
11
15
12
15
13
15
14
15
15
15
16
15
2
15
3
15
4
15
5
15
6
15
7
15
8
15
9
15
10
15
11
15
12
15
13
15
14
15
15
15
16
15
2
15
3
15
4
15
5
15
6
15
7
15
8
15
9
15
10
15
11
15
12
15
13
15
14
15
15
15
16
15
2
15
3
15
4
15
5
15
6
15
7
15
8
15
9
15
10
15
11
15
12
15
13
15
14
15
15
15
16
15
2
15
3
15
4
15
5
15
6
15
7
15
8
15
9
15
10
15
11
15
12
15
13
15
14
15
15
15
16
15
2
15
3
15
4
15
5
15
6
15
7
15
8
15
9
15
10
15
11
15
12
15
13
15
14
15
15
15
16
15
2
15
3
15
4
15
5
15
6
15
7
15
8
15
9
15
10
15
11
15
12
15
13
15
14
15
15
15
16
15
2
15
3
15
4
15
5
15
6
15
7
15
8
15
9
15
10
15
11
15
12
15
13
15
14
15
15
15
16
15
2
15
3
15
4
15
5
15
6
15
7
15
8
15
9
15
10
15
11
15
12
15
13
15
14
15
15
15
16
15
2
15
3
15
4
15
5
15
6
15
7
15
8
15
9
15
10
15
11
15
12
15
13
15
14
15
15
15
16
15
2
15
3
15
4
15
5
15
6
15
7
15
8
15
9
15
10
15
11
15
12
15
13
15
14
15
15
15
16
15
2
15
3
15
4
1

0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
1
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2


In [80]:
pd.DataFrame(fund_returns['ETH40, BTC40, USD20 @ 7']).T.head(15)

eth_price   btc_price   usd_price
2017-01-01  400.000000  400.000000  200.000000
2017-01-02  397.522167  416.071053  200.000000
2017-01-03  428.082109  418.954714  200.000000
2017-01-04  507.227013  442.847903  200.000000
2017-01-05  509.121827  430.489357  200.000000
2017-01-06  486.189724  382.284436  200.000000
2017-01-07  474.966598  356.497918  200.000000
2017-01-08  485.120855  374.374967  200.000000
2017-01-09  442.431024  415.378173  211.899164
2017-01-10  441.285050  419.277205  211.899164
2017-01-11  425.920504  393.287856  211.899164
2017-01-12  403.340563  364.344271  211.899164
2017-01-13  406.693599  375.492023  211.899164
2017-01-14  407.797130  384.997808  211.899164
2017-01-15  412.932793  380.596066  211.899164

In [81]:
fund_computed_plot = []
for fund in fund_returns:
    print(fund)
    fund_df = pd.DataFrame(fund_returns[fund]).T
    
    fund_value = fund_df.sum(axis=1)
    fund_performance = (fund_value.iloc[-1] / fund_value.iloc[0]) * 100
    fund_performance = round(fund_performance, 3)
    fund_plot = go.Scatter(
        x = fund_value.index,
        y = fund_value.tolist(),
        mode = 'lines',
        name = '{0} -> {1}%'.format(fund, fund_performance))
    fund_computed_plot.append(fund_plot)

ETH40, BTC40, USD20 @ 7
ETH25, BTC25, USD50 @ 30
ETH50, BTC50 @ 15
ETH50, BTC50 @ HODL
ETH100 @ HODL
BTC100 @ HODL


In [82]:
layout = go.Layout(
    title = "Different Portfolio Rebalancing Strategies Over time",
    autosize=True,
    showlegend=True,
    legend=dict(x=0.7, y=0.9))

fig = dict(data=fund_computed_plot, layout = layout)
py.iplot(fig)

In [123]:
THR = 0.05

In [124]:
initial_allocation

array([   125.        ,      0.12873486,     15.18280092,  19201.22887865,
           28.48029164,     11.00739697,      9.23736329, 558035.71428571])

In [129]:
hodl = {}
rb = {}

current_allocation = initial_allocation

for i, current_price in all_coins_df.iterrows():
    # hodl positions
    hodl[i] = initial_allocation * current_price
    
    # current positions
    current_positions = current_allocation * current_price
    rb[i] = current_positions
    
    # rebalance
    current_portfolio_value = current_positions.sum()
    current_weights = current_positions / current_portfolio_value
    weights_diff = np.abs(current_weights - initial_weights)
    if any(weights_diff > THR) and current_price.min() > 0:
#         print(i, 'rebalancing')
        current_allocation = current_portfolio_value * initial_weights / current_price

hodl = pd.DataFrame(hodl).T
rb = pd.DataFrame(rb).T

In [126]:
hodl_value = hodl.sum(axis=1)
rb_value = rb.sum(axis=1)

hodl_perf = hodl_value.iloc[-1] / hodl_value.iloc[0]
rb_perf = rb_value.iloc[-1] / rb_value.iloc[0]

In [127]:
hodlInfo = go.Scatter(
        x = hodl_value.index,
        y = hodl_value.tolist(),
        mode = 'lines',
        name = 'hodl {:.1f}%'.format(hodl_perf * 100))

rebalanceInfo = go.Scatter(
        x = rb_value.index,
        y = rb_value.tolist(),
        mode = 'lines',
        name = 'rebalance {:.1f}%'.format(rb_perf * 100))

In [130]:
layout = go.Layout(
    title = "Threshold rebalencing",
    autosize=True,
    showlegend=True,
    legend=dict(x=0.8, y=0.9))

fig = dict(data=[hodlInfo, rebalanceInfo], layout = layout)
py.iplot(fig)